export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAILED = 'GET_PRODUCTS_FAILED';
export const GET_ARTICLES = 'GET_ARTICLES';
export const GET_ARTICLES_SUCCESS = 'GET_ARTICLES_SUCCESS';
export const GET_ARTICLES_FAILED = 'GET_ARTICLES_FAILED';

export const ADD_NEW_ARTICLE = 'ADD_NEW_ARTICLE';
export const ADD_NEW_ARTICLE_SUCCESS = 'ADD_NEW_ARTICLE_SUCCESS';
export const ADD_NEW_ARTICLE_FAILED = 'ADD_NEW_ARTICLE_FAILED';

export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const ADJUST_QTY = 'ADJUST_QTY';
export const LOAD_CURRENT_ITEM = 'LOAD_CURRENT_ITEM';
export const LOAD_CURRENT_ITEM_SUCCESS = 'LOAD_CURRENT_ITEM_SUCCESS';
